### PR TITLE
Make dependency installation more deterministic

### PR DESCRIPTION
**Pull request by bryanenders**
Fixes https://github.com/mozilla/hubs-compose/issues/34

Why
---
Although `npm install --no-save` doesn’t alter `package-lock.json`, it doesn’t honor `package-lock.json` any more than `npm install`.  The clean install `npm ci` is time-consuming and should only be run if `package-lock.json` has changed.

How
---
* Create `conditional-npm-ci`
* Use `conditional-npm-ci` for Dialog, Hubs Admin, and Hubs Client

### CODE REVIEW

**Review by johnshaughnessy — APPROVED** [review]
Is it important to avoid rerunning `npm ci` when people only need to run this script once?

**Comment by bryanenders** [comment]
You may want to run `bin/init` anytime you change service dependencies. I often run **$** `bin/services-update && bin/init`.

**Comment by bryanenders** [comment]
@johnshaughnessy You may want to run `bin/init` when you change service dependencies. I often run **$** `bin/services-update && bin/init`.

**Comment by bryanenders** [comment]
Thanks for asking! I added a line to the README.

**Pull request merged**
